import slideCampus1 from './assets/slide-campus-1.png'
import slideCampus2 from './assets/slide-campus-2.png'
import slideCampus3 from './assets/slide-campus-3.jpg'
import slideCampus4 from './assets/slide-campus-4.jpg'

export const slides = [
  { image: slideCampus1, title: '校园主视图', credit: '摄影：周嵩娜' },
  { image: slideCampus2, title: '主楼视角', credit: '摄影：郭子昂' },
  { image: slideCampus3, title: '校园风景', credit: '摄影：宗琪琪' },
  { image: slideCampus4, title: '教学场景', credit: '摄影：郭子昂' },
]

export const overviewStats = [
  {
    label: '办学渊源',
    value: '1904 肇始，1919 正式成立',
    detail: '由严修、张伯苓秉承教育救国理念创办，是中国近代教育史上的重要里程碑，形成了"爱国、敬业、创新、乐群"的南开品格。',
  },
  {
    label: '学校定位',
    value: '教育部直属重点综合性大学',
    detail: '国家"双一流"建设高校，"985工程"和"211工程"重点建设大学，以基础研究和应用研究并重，培养具有家国情怀和国际视野的创新人才。',
  },
  {
    label: '南开精神',
    value: '允公允能，日新月异',
    detail: '"允公"是大公无私，"允能"是培养能力，"日新月异"是与时俱进、追求卓越。这一校训激励着南开学子不断奋进。',
  },
  {
    label: '办学格局',
    value: '一校三区',
    detail: '八里台校区承载百年底蕴，津南校区展现现代风貌，泰达校区聚焦特色发展。三校区协同并进，构建开放多元的办学格局。',
  },
]

export const mathTimeline = [
  {
    year: '1920',
    title: '南开数学起点',
    description:
      '南开数学系由姜立夫创立，是中国高校较早设立的数学系之一，也奠定了学校深厚的数学传统。',
  },
  {
    year: '1985',
    title: '陈省身数学研究所',
    description:
      '陈省身数学研究所由陈省身先生倡议创办并亲任所长，成为南开数学走向世界的重要学术名片。',
  },
  {
    year: '1997',
    title: '数学科学学院成立',
    description:
      '数学学科形成更完整的人才培养和科研组织结构，为建模训练提供坚实的基础课程与学术支持。',
  },
  {
    year: '今天',
    title: '服务建模训练',
    description:
      '数学、统计与数据科学等学科资源，为数学建模协会的培训、选拔、竞赛和复盘提供了稳定土壤。',
  },
]

export const associationCards = [
  {
    kicker: '组织架构',
    title: '委员会',
    description: '了解协会的领导机构和各部门成员，感受严谨高效的组织体系。',
    action: '查看委员会',
    href: '/committee',
  },
  {
    kicker: '资料中心',
    title: '建模资料',
    description: '汇集历年竞赛真题、优秀论文、常用模型和工具教程，助力你的建模之路。',
    action: '浏览资料库',
    href: '/materials',
  },
  {
    kicker: '竞赛训练',
    title: '校队培训',
    description: '系统的培训课程、模拟竞赛和经验分享，为校赛和国赛做好充分准备。',
    action: '了解培训',
    href: '/#resources',
  },
  {
    kicker: '招新纳贤',
    title: '加入我们',
    description: '无论你是建模新手还是高手，只要对数学建模有热情，欢迎加入我们的大家庭！',
    action: '联系我们',
    href: '#contact',
  },
]

export const materialCards = [
  {
    title: '飞书建模资料总入口',
    description:
      '汇集历年竞赛真题、优秀论文、常用模型和工具教程，助力你的建模之路。',
    href: 'https://nankai.feishu.cn/wiki/CMSXwe42YiGJtpkxSYHcaO5inwb',
    meta: '外部资料库',
  },
]

export const awardPapers = [
  {
    year: '2025',
    title: '2025年全国大学生数学建模竞赛',
    description: '获奖论文合集',
    papers: [
      {
        problem: '省奖',
        title: '25省奖论文',
        prize: '省级获奖',
        team: '全省获奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '25省奖A题论文',
            prize: '省级获奖',
            team: 'A题省奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '2025国赛论文-2',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/HkMSbqKUWoEQEqx3JnccpDS2nqd',
              },
              {
                problem: '论文',
                title: '烟幕投放决策研究-约束优化下基于改进粒子群算法',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/NqXXbIwlJowj7cxxqmpca19ynJc',
              },
              {
                problem: '论文',
                title: 'A论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/BlaJbgLSmoRry0xasopcE1V6nTg',
              },
              {
                problem: '论文',
                title: 'A题(2)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/TAneb8ss3oJHrzxcCGbcj3k6nC6',
              },
              {
                problem: '论文',
                title: 'A题-贾天博',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/I8EJbBQ9noeUovxNad1cx7mUnCd',
              },
              {
                problem: '论文',
                title: 'A题-姜苏桐',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/TBs9b4uZ2o38FCxZ2yHc1BScnmg',
              },
              {
                problem: '论文',
                title: 'A题',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/JgTKbzJg1ocYxpx87HVcs66Znuh',
              },
              {
                problem: '论文',
                title: '基于粒子群优化的多无人机烟幕干扰投放模型效能最大化研究',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/JXpSbUSkpoABJDxY8cDcUE0mnsb',
              },
              {
                problem: '论文',
                title: '基于遗传算法的多机协同烟幕干扰弹投放优化 第五版',
                prize: '省级获奖',
                team: 'DOCX',
                href: 'https://nankai.feishu.cn/file/BeR2bVcZ3ofqAJxq3rzc8A4Xnhc',
              },
              {
                problem: '论文',
                title: '基于遗传算法的烟幕干扰弹投放策略设计',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Tz3TbkAdWohVYlxErI8cRu2KnQE',
              },
              {
                problem: '论文',
                title: '论文(2)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Nut9bvJo3onVkKxc8lFcJifjnZg',
              },
              {
                problem: '论文',
                title: '数学建模',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/QTdAbOfNJoB7bwxhBM9cipCXn8d',
              },
              {
                problem: '论文',
                title: '烟幕干扰弹的投放策略',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/I7t1bFf3voSKcCxrWDUcHiW2nxc',
              },
            ],
          },
          {
            problem: 'B题',
            title: '25省奖B题论文',
            prize: '省级获奖',
            team: 'B题省奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: 'B题-牛若水',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/U6TWbR9lRoKcNvx3Jh3cXSovnyo',
              },
              {
                problem: '论文',
                title: 'B题-邢博文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/SYokbil8wo3io5xljwmcJQS2nCf',
              },
              {
                problem: '论文',
                title: 'B题',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/MiFnbRy7Po24hdxHQaxcCNpVngi',
              },
              {
                problem: '论文',
                title: '基于红外干涉法的碳化硅外延层厚度测定',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Zpx6boSC1oGZsCxF0lccKGRgnnF',
              },
            ],
          },
          {
            problem: 'C题',
            title: '25省奖C题论文',
            prize: '省级获奖',
            team: 'C题省奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: 'C题(2)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/WJj6bGyENoQhUUxG5mocc7qnnve',
              },
              {
                problem: '论文',
                title: 'C题(3)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/RBBpbOt9moQMPIx2J4KcyJmWnwb',
              },
              {
                problem: '论文',
                title: 'C题--宋忻洁',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Iw0cb4CaToqKDIxKniwc4SNynrf',
              },
              {
                problem: '论文',
                title: 'C题-戴子河',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Jb4LbwWi4oz8umxXahdcl1LYncf',
              },
              {
                problem: '论文',
                title: 'C题-董梦婷',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/SLVvb3QWlohRrtxEVAXcLHMXnJf',
              },
              {
                problem: '论文',
                title: 'C题-乔培瑞，卢俊超，朱梓延',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/ZkGnbo1Pzo2awjxlUcJcXxnMnDd',
              },
              {
                problem: '论文',
                title: 'C题-杨泰齐',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/IiRebNFLnoefz5xpX6YcAkManDg',
              },
              {
                problem: '论文',
                title: 'C题',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/NysWbDn6FoCQUlxeflEcMApLnqd',
              },
              {
                problem: '论文',
                title: 'NIPT个性化决策框架：从分群预测到无监督异常',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/S0sRbQJDXoXl7hxhLpic7FyTncg',
              },
              {
                problem: '论文',
                title: '论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/MksebfwFGoIQGWx57gncFEDSnlb',
              },
              {
                problem: '论文',
                title: '论文(1)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/LBbybFbmSoQUSFxWlKQcX41knfd',
              },
              {
                problem: '论文',
                title: '数据驱动下的NIPT检测时点优化与异常判定',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/AC6XbzojEoPxe1x6v36cBXZXnRR',
              },
            ],
          },
        ],
      },
      {
        problem: '国二',
        title: '2025国赛二等奖',
        prize: '全国二等奖',
        team: '国赛二等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2025国赛二等奖A题',
            prize: '全国二等奖',
            team: 'A题国赛二等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '基于烟幕干扰弹的投放策略略问题',
                prize: '全国二等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Eg3GbZuL1oNUFQxDtsWcaY8mnxf',
              },
            ],
          },
          {
            problem: 'C题',
            title: '2025国赛二等奖C题',
            prize: '全国二等奖',
            team: 'C题国赛二等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '论文',
                prize: '全国二等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/JpeBb0xVxo5oMCxW9pOclNn8nyb',
              },
            ],
          },
        ],
      },
      {
        problem: '国一',
        title: '2025国赛一等奖',
        prize: '全国一等奖',
        team: '国赛一等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2025国赛一等奖A题',
            prize: '全国一等奖',
            team: 'A题国赛一等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '2025A (9)',
                prize: '全国一等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/G8I1bbnsbo45ghxtQcOczvJInhe',
              },
            ],
          },
          {
            problem: 'B题',
            title: '2025国赛一等奖B题',
            prize: '全国一等奖',
            team: 'B题国赛一等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '国赛',
                prize: '全国一等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/JIfabmBKpoKEv0xB6VvczYC6n2g',
              },
            ],
          },
          {
            problem: 'C题',
            title: '2025国赛一等奖C题',
            prize: '全国一等奖',
            team: 'C题国赛一等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '基于多模型融合与风险控制的NIPT检测策略优化研究',
                prize: '全国一等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/UsDXbs8I7o3sl0x0ktucfJeQnee',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    year: '2024',
    title: '2024年全国大学生数学建模竞赛',
    description: '获奖论文合集',
    papers: [
      {
        problem: '省奖',
        title: '24省奖论文',
        prize: '省级获奖',
        team: '全省获奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '24省奖A题论文',
            prize: '省级获奖',
            team: 'A题省奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '基于二分法的链状多体系统在等距螺旋线运动求解模型',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/VLSIb4Uhqoed3FxQlfocCVoTnub',
              },
              {
                problem: '论文',
                title: '基于迭代和碰撞检测算法的盘龙模型研究',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/WaNpbJkD7ooqrnxLTqOcbeL4n3c',
              },
              {
                problem: '论文',
                title: '国赛模板',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/G9fCbbUl3oJoyVx9YV8cfhZxnCa',
              },
              {
                problem: '论文',
                title: '我的论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/PYEyb0QheozMXRxhsAdcQkBmnSw',
              },
            ],
          },
          {
            problem: 'B题',
            title: '24省奖B题论文',
            prize: '省级获奖',
            team: 'B题省奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '国赛论文模版',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/IZO8bm4KnoPffLxE4A4cSyasn9f',
              },
              {
                problem: '论文',
                title: '2024国赛电子版',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/R1Ilb3024ojifAxmSzmc6m8hnuc',
              },
              {
                problem: '论文',
                title: 'B题论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/HJf2b4AN7oWLWvxcZ2hcI8QJnoc',
              },
              {
                problem: '论文',
                title: '国赛',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/C5cebYVlMoyZDPxn0oxc9bULn9b',
              },
              {
                problem: '论文',
                title: '国赛复现-4',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/XKc0bPclroNfV4xeobDcTj4dnYc',
              },
              {
                problem: '论文',
                title: '国赛提交版',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/XUEzby8kNoUkJ5xi89ucOpPrn5g',
              },
              {
                problem: '论文',
                title: '基于成本效益分析的多路径生产决策优化',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/HveAbfxotoMb4ixvgy3cwfulnkb',
              },
              {
                problem: '论文',
                title: '基于成本最小化的多阶段生产决策模型',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/PrXgbxensogDpIxm2jTciXgVneh',
              },
              {
                problem: '论文',
                title: '基于动态过程的生产决策优化',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/M02jblg5voplv4xRF4kcywpvnKT',
              },
              {
                problem: '论文',
                title: '基于分布式优化模型的企业生产决策方案',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/NcOwbsD1DotvTJxUx6XcqZKnniT',
              },
              {
                problem: '论文',
                title: '基于改进的序贯概率比检验与多层决策树的多工序生产决策问题研究',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/FNaJbCjgnoTEMSxq9dscSA0onFc',
              },
              {
                problem: '论文',
                title: '基于序贯概率比检验与概率评估的生产决策模型',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/XmdRbUPLToUiwjxPOqpcy6mFnxx',
              },
              {
                problem: '论文',
                title: '基于序贯检验的生产过程决策模型',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/KL39bpVjAoatK6xolCJcAsjSn4d',
              },
              {
                problem: '论文',
                title: '论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/XegNbsfCsopM1Yx0fFzcSmtznLc',
              },
              {
                problem: '论文',
                title: '论文(1)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/XegNbsfCsopM1Yx0fFzcSmtznLc',
              },
              {
                problem: '论文',
                title: '论文2',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/NtF9bIANmoh8QFxAvqcc1gZ7nBd',
              },
              {
                problem: '论文',
                title: '企业生产过程的决策研究',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Ac3wbFWcmor7pUxwAelcZVOinHg',
              },
              {
                problem: '论文',
                title: '全国大学生数学建模竞赛论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Y1GPbnx7aoawexx8zGccoez5n7g',
              },
              {
                problem: '论文',
                title: '生产决策优化_基于抽样检测与动态规划的决策模型',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/HpQRbsdzko10LFx7Ngvcs3fynxh',
              },
              {
                problem: '论文',
                title: '基于抽样检测与动态规划的决策模型',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/ONZRbqEy6o9nGkx4Cr4cYiU6n6d',
              },
            ],
          },
          {
            problem: 'C题',
            title: '24省奖C题论文',
            prize: '省级获奖',
            team: 'C题省奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: 'C228',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/G6wLbNItRorQmrx7FOLc1cwTnbg',
              },
              {
                problem: '论文',
                title: '国赛C题',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/WIOSb0kh0oX2uIxVyTlcOqnSn9e',
              },
              {
                problem: '论文',
                title: '国赛论文',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Yc0Ibk2XQoXtDlxrhQ9cZQ7BnEg',
              },
              {
                problem: '论文',
                title: '基于线性规划模型的乡村农作物种植策略优化',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/U8QlbbvB4oBS9GxoGzLc454Tnyb',
              },
              {
                problem: '论文',
                title: '基于优化算法的某乡村农作物种植决策研究',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/SRXvbLNVBoBMPLxJwFNcDxi5nPd',
              },
              {
                problem: '论文',
                title: '全国大学生数学建模竞赛论文(1)',
                prize: '省级获奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/CtIDbA5T7oGgy3xCq8CcG7LbnSh',
              },
            ],
          },
        ],
      },
      {
        problem: '国二',
        title: '2024国赛二等奖',
        prize: '全国二等奖',
        team: '国赛二等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2024国赛二等奖A题',
            prize: '全国二等奖',
            team: 'A题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2024国赛二等奖B题',
            prize: '全国二等奖',
            team: 'B题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2024国赛二等奖C题',
            prize: '全国二等奖',
            team: 'C题国赛二等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '2024国赛-雷鸣远-胡峻玮-陈星烨',
                prize: '全国二等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/C4bIbcpDVoPhGxxZVXRcNUE9n4d',
              },
            ],
          },
        ],
      },
      {
        problem: '国一',
        title: '2024国赛一等奖',
        prize: '全国一等奖',
        team: '国赛一等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2024国赛一等奖A题',
            prize: '全国一等奖',
            team: 'A题国赛一等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '2024国赛一等奖A题论文',
                prize: '全国一等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/J1YobcMGMoJx9fxySCMcFDsynCd',
              },
            ],
          },
          {
            problem: 'B题',
            title: '2024国赛一等奖B题',
            prize: '全国一等奖',
            team: 'B题国赛一等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '基于抽样模拟与动态规划的企业最优决策研究_纸质版',
                prize: '全国一等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/PCeGbOmLZoOfHLxdCp5cBluPnWc',
              },
            ],
          },
          {
            problem: 'C题',
            title: '2024国赛一等奖C题',
            prize: '全国一等奖',
            team: 'C题国赛一等奖队伍论文',
            hasChildren: true,
            children: [
              {
                problem: '论文',
                title: '建模国赛(3)',
                prize: '全国一等奖',
                team: 'PDF',
                href: 'https://nankai.feishu.cn/file/Ke1PbBmzjowXMMxARarcUtV8n7f',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    year: '2023',
    title: '2023年全国大学生数学建模竞赛',
    description: '获奖论文合集',
    papers: [
      {
        problem: '省奖',
        title: '23省奖论文',
        prize: '省级获奖',
        team: '全省获奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '23省奖A题论文',
            prize: '省级获奖',
            team: 'A题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '23省奖B题论文',
            prize: '省级获奖',
            team: 'B题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '23省奖C题论文',
            prize: '省级获奖',
            team: 'C题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
      {
        problem: '国二',
        title: '2023国赛二等奖',
        prize: '全国二等奖',
        team: '国赛二等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2023国赛二等奖A题',
            prize: '全国二等奖',
            team: 'A题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2023国赛二等奖B题',
            prize: '全国二等奖',
            team: 'B题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2023国赛二等奖C题',
            prize: '全国二等奖',
            team: 'C题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
      {
        problem: '国一',
        title: '2023国赛一等奖',
        prize: '全国一等奖',
        team: '国赛一等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2023国赛一等奖A题',
            prize: '全国一等奖',
            team: 'A题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2023国赛一等奖B题',
            prize: '全国一等奖',
            team: 'B题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2023国赛一等奖C题',
            prize: '全国一等奖',
            team: 'C题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
    ],
  },
  {
    year: '2022',
    title: '2022年全国大学生数学建模竞赛',
    description: '获奖论文合集',
    papers: [
      {
        problem: '省奖',
        title: '22省奖论文',
        prize: '省级获奖',
        team: '全省获奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '22省奖A题论文',
            prize: '省级获奖',
            team: 'A题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '22省奖B题论文',
            prize: '省级获奖',
            team: 'B题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '22省奖C题论文',
            prize: '省级获奖',
            team: 'C题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
      {
        problem: '国二',
        title: '2022国赛二等奖',
        prize: '全国二等奖',
        team: '国赛二等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2022国赛二等奖A题',
            prize: '全国二等奖',
            team: 'A题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2022国赛二等奖B题',
            prize: '全国二等奖',
            team: 'B题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2022国赛二等奖C题',
            prize: '全国二等奖',
            team: 'C题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
      {
        problem: '国一',
        title: '2022国赛一等奖',
        prize: '全国一等奖',
        team: '国赛一等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2022国赛一等奖A题',
            prize: '全国一等奖',
            team: 'A题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2022国赛一等奖B题',
            prize: '全国一等奖',
            team: 'B题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2022国赛一等奖C题',
            prize: '全国一等奖',
            team: 'C题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
    ],
  },
  {
    year: '2021',
    title: '2021年全国大学生数学建模竞赛',
    description: '获奖论文合集',
    papers: [
      {
        problem: '省奖',
        title: '21省奖论文',
        prize: '省级获奖',
        team: '全省获奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '21省奖A题论文',
            prize: '省级获奖',
            team: 'A题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '21省奖B题论文',
            prize: '省级获奖',
            team: 'B题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '21省奖C题论文',
            prize: '省级获奖',
            team: 'C题省奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
      {
        problem: '国二',
        title: '2021国赛二等奖',
        prize: '全国二等奖',
        team: '国赛二等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2021国赛二等奖A题',
            prize: '全国二等奖',
            team: 'A题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2021国赛二等奖B题',
            prize: '全国二等奖',
            team: 'B题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2021国赛二等奖C题',
            prize: '全国二等奖',
            team: 'C题国赛二等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
      {
        problem: '国一',
        title: '2021国赛一等奖',
        prize: '全国一等奖',
        team: '国赛一等奖队伍论文',
        hasChildren: true,
        children: [
          {
            problem: 'A题',
            title: '2021国赛一等奖A题',
            prize: '全国一等奖',
            team: 'A题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'B题',
            title: '2021国赛一等奖B题',
            prize: '全国一等奖',
            team: 'B题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
          {
            problem: 'C题',
            title: '2021国赛一等奖C题',
            prize: '全国一等奖',
            team: 'C题国赛一等奖队伍论文',
            href: 'https://nankai.feishu.cn/docx/XXXXXXXX',
          },
        ],
      },
    ],
  },
]

export const resourceColumns = [
  {
    title: '入门导学',
    items: ['建模基本流程', '常见模型梳理', '工具链安装指引'],
  },
  {
    title: '竞赛训练',
    items: ['历年赛题归档', '模拟赛资料', '复盘与讲评记录'],
  },
  {
    title: '写作模板',
    items: ['LaTeX 模板', '论文结构示意', '图表与附录建议'],
  },
  {
    title: '经验沉淀',
    items: ['组队建议', '时间管理方法', '展示答辩与复盘心得'],
  },
]

export const campusCards = [
  {
    campus: '八里台校区',
    address: '天津市南开区卫津路 94 号',
    postcode: '300071',
    note: '坐落于天津市中心，是南开大学的发源地，承载着百年校史的厚重底蕴。',
  },
  {
    campus: '津南校区',
    address: '天津海河教育园区同砚路 38 号',
    postcode: '300350',
    note: '现代化的新校区，拥有一流的教学科研设施，是创新人才培养的重要基地。',
  },
  {
    campus: '泰达校区',
    address: '天津经济技术开发区宏达街 23 号',
    postcode: '300457',
    note: '位于滨海新区，以产学研融合为特色，为学生提供丰富的实践机会。',
  },
]

export const committeeOverview = [
  {
    title: '常务理事会',
    members: ['金莫迪', '江绮佳', '王飞鸣', '张家英', '高艺楠', '皮子谦', '姜政旭'],
  },
  {
    title: '理事会',
    members: [
      '王飞鸣',
      '王婧',
      '牛若水',
      '史峰源',
      '皮子谦',
      '江绮佳',
      '刘凯',
      '刘懿堂',
      '刘咏璇',
      '安芮滋',
      '张家英',
      '张铭渊',
      '张语泽',
      '苏荷',
      '陈祎缘',
      '李思瑶',
      '汪星宇',
      '张文欣',
      '张启乐',
      '张启乐',
      '金莫迪',
      '金涛',
      '孟琳杰',
      '姜政旭',
      '高艺楠',
      '高昊泽',
      '景子夏',
      '武宇航',
    ],
  },
]

export const committeeDepartments = [
  {
    name: '学术部',
    roles: [
      { title: '分管副主席', members: ['王飞鸣'] },
      { title: '部门负责人', members: ['张语泽', '武宇航'] },
      { title: '干事', members: ['暂无'] },
    ],
  },
  {
    name: '竞赛部',
    roles: [
      { title: '分管副主席', members: ['高艺楠', '李思瑶'] },
      { title: '部门负责人', members: ['牛若水', '景子夏'] },
      {
        title: '干事',
        members: [
          '李若霖',
          '王昊成',
          '贺红源',
          '张卓翔',
          '王梓杰',
          '鲍中正',
          '关宇轩',
          '阮启涵',
          '刘哲维',
          '焦赫',
          '白一然',
          '张跃然',
          '郑堃彤',
          '李冠桐',
          '朱奕妃',
          '张煜铭',
          '刘沛希',
        ],
      },
    ],
  },
  {
    name: '策划部',
    roles: [
      { title: '分管副主席', members: ['张家英'] },
      { title: '部门负责人', members: ['高昊泽', '孟炜杰'] },
      { title: '专职副部长', members: ['陈祎缘'] },
      {
        title: '干事',
        members: [
          '郝梓博',
          '周星橙',
          '姜兴雨',
          '袁航宇',
          '路航',
          '李止峰',
          '赵欣然',
          '徐宰盈',
          '徐宰盈',
          '禹益菲',
          '魏卫欣',
          '赵宇玥',
          '邓睿宸',
          '李梦伶',
          '齐成慧',
          '刘蕙霖',
          '王港',
          '魏湘宇',
        ],
      },
    ],
  },
  {
    name: '宣传部',
    roles: [
      { title: '分管副主席', members: ['张文欣', '李思瑶'] },
      { title: '部门负责人', members: ['安芮滋'] },
      {
        title: '干事',
        members: [
          '陈思润',
          '薛婷月',
          '章若凡',
          '陈赵文',
          '谭果果',
          '高睿',
          '张楚涵',
          '高翰泽',
          '王梓瑶',
          '张城祎',
          '张嘉祐',
          '陈俊儒',
          '吕硕',
          '章开元',
          '孙竞择',
          '刘子琦',
        ],
      },
    ],
  },
  {
    name: '办公部',
    roles: [
      { title: '分管副主席', members: ['皮子谦'] },
      { title: '部门负责人', members: ['王婧', '刘咏璇'] },
      {
        title: '干事',
        members: [
          '卢雨菲',
          '王睿心',
          '陈谦',
          '孟远晴',
          '王衡',
          '魏鑫妤',
          '孟子玉',
          '张芝煊',
          '何璟婕',
          '唐欣媛',
          '范婷钰',
          '张馨方',
          '缪宇佳',
          '刘锦宜',
        ],
      },
    ],
  },
  {
    name: '研究生事务办公室',
    roles: [
      { title: '分管副主席', members: ['江绮佳'] },
      { title: '部门负责人', members: ['姜政旭'] },
      { title: '专职副部长', members: ['汪星宇'] },
    ],
  },
  {
    name: '对外联络办公室',
    roles: [
      { title: '分管副主席', members: ['张启乐', '皮子谦'] },
      { title: '部门负责人', members: ['张启乐'] },
      {
        title: '干事',
        members: [
          '宋雅萌',
          '皮子涵',
          '陈雨萱',
          '曾正',
          '李姿璇',
          '杜稀涵',
          '赵家胜',
          '周玺',
          '郭真宇',
          '贾美焕',
          '陈叶桐',
          '王平',
          '刘彦伯',
        ],
      },
    ],
  },
]

export const footerLinks = [
  { label: '南开大学官网', href: 'https://www.nankai.edu.cn/' },
  { label: '陈省身数学研究所', href: 'https://www.cim.nankai.edu.cn/' },
  { label: '南开新闻网', href: 'https://news.nankai.edu.cn/' },
]
